In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
x

tensor([[-0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.1376,  0.0000],
        [ 0.0000,  0.0000, -0.1329],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [4]:
x = torch.rand(5, 3)
x

tensor([[0.3148, 0.5286, 0.3395],
        [0.5076, 0.7143, 0.4633],
        [0.5434, 0.6790, 0.7487],
        [0.4349, 0.8585, 0.4036],
        [0.2689, 0.1517, 0.6851]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
type(x)

torch.Tensor

In [7]:
x.dtype

torch.int64

In [8]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

###  Or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g type, unless new values are provided by user

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.3242,  1.7395, -0.2575],
        [-1.0546,  0.8964,  0.6955],
        [-0.9904, -0.6639, -1.8342],
        [-0.2962,  0.1437,  0.0456],
        [ 0.0438,  0.9767,  1.3233]])

In [11]:
x.size()

torch.Size([5, 3])

In [12]:
y = torch.rand(5, 3)
x + y

tensor([[ 0.6197,  2.2371,  0.4832],
        [-0.5399,  1.0098,  1.1234],
        [-0.9431, -0.3914, -1.3928],
        [ 0.6362,  0.8238,  0.7125],
        [ 0.4244,  1.1034,  1.5891]])

In [13]:
torch.add(x, y)

tensor([[ 0.6197,  2.2371,  0.4832],
        [-0.5399,  1.0098,  1.1234],
        [-0.9431, -0.3914, -1.3928],
        [ 0.6362,  0.8238,  0.7125],
        [ 0.4244,  1.1034,  1.5891]])

In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.6197,  2.2371,  0.4832],
        [-0.5399,  1.0098,  1.1234],
        [-0.9431, -0.3914, -1.3928],
        [ 0.6362,  0.8238,  0.7125],
        [ 0.4244,  1.1034,  1.5891]])

In [18]:
# Addition x to y
y.add_(x)
y

tensor([[ 0.6197,  2.2371,  0.4832],
        [-0.5399,  1.0098,  1.1234],
        [-0.9431, -0.3914, -1.3928],
        [ 0.6362,  0.8238,  0.7125],
        [ 0.4244,  1.1034,  1.5891]])

In [19]:
# Addition x to y
y.add(x)
y

tensor([[ 0.6197,  2.2371,  0.4832],
        [-0.5399,  1.0098,  1.1234],
        [-0.9431, -0.3914, -1.3928],
        [ 0.6362,  0.8238,  0.7125],
        [ 0.4244,  1.1034,  1.5891]])

## NOTE
Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [22]:
x[:, 1]

tensor([ 1.7395,  0.8964, -0.6639,  0.1437,  0.9767])

Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [23]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have one element tensor, use .item() to get the value as a Python number

In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2515])
-0.251503407955


### NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.
### Converting a Torch Tensor to a NumPy Array

In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [27]:
type(b)

numpy.ndarray

In [28]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
Tensors can be moved onto any device using the ``.to`` method

In [36]:
# let us run this cell only if CUDA is avaiable
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")   # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) # ``.to`` can also change dtype together!

tensor([0.7485], device='cuda:0')
tensor([0.7485], dtype=torch.float64)
